# Generated by Django 5.2.8 on 2025-11-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_type', models.CharField(choices=[('cad', 'CAD модель'), ('doc', 'Документ'), ('analysis', 'Анализ/FEA'), ('spec', 'Спецификация'), ('other', 'Другое')], default='other', max_length=20)),
                ('section', models.CharField(choices=[('files', 'Файлы и документы'), ('configurations', 'Конфигурации'), ('powertrain', 'Силовая установка'), ('chassis', 'Шасси и подвеска'), ('aerodynamics', 'Аэродинамика'), ('battery', 'Батарея и BMS'), ('telemetry', 'Телеметрия'), ('calculations', 'Расчеты и симуляции'), ('versioning', 'Версионность')], default='files', max_length=50)),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('size', models.PositiveIntegerField(default=0, editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
