# Generated by Django 5.2.8 on 2025-11-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='size',
            field=models.PositiveBigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='version',
            field=models.CharField(blank=True, default='v1.0', max_length=20),
        ),
    ]
